platform :ios,'6.0'


pod 'GoogleAnalytics-iOS-SDK','2.0beta4'
pod 'JSONKit'
pod 'BlocksKit'
pod 'OHAttributedLabel'
pod 'RegexKitLite'
pod 'ASIHTTPRequest'
pod 'iRate'
pod 'iVersion'
pod 'iNotify'
pod 'MBProgressHUD',:head
pod 'Reachability'
pod 'SDWebImage'
pod 'SVWebViewController'
pod 'SSKeychain'
pod 'IAPManager'
pod 'HPGrowingTextView'
pod 'MagicalRecord'
pod 'SFHFKeychainUtils'
pod 'UIGlossyButton'
pod 'Slash'
pod 'NullSafe'
