platform :ios,'6.0'


pod 'JSONKit',:git=>'https://github.com/peyoo/JSONKitWithoutXcode4Warnings.git'
pod 'BlocksKit'
pod 'OHAttributedLabel'
pod 'RegexKitLite'
pod 'ASIHTTPRequest'
pod 'iRate'
pod 'iVersion'
pod 'iNotify'
pod 'MBProgressHUD'
pod 'Reachability'
pod 'SDWebImage'
pod 'SVWebViewController'
pod 'SSKeychain'
pod 'IAPManager'
pod 'HPGrowingTextView'
pod 'MagicalRecord'
pod 'SFHFKeychainUtils'
pod 'UIGlossyButton'
pod 'Slash'
pod 'NullSafe'